# Site settings
title: logspace.io
description: "Collect and analyze events"
baseurl: ""
url: ""

# Build settings
markdown: redcarpet
permalink: pretty
exclude: [node_modules, scripts, bower_components, jsdoc-template]

sass:
  sass_dir: assets/css
  style: :compressed

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
